### ISSUE TITLE
Cascading select for location

### ISSUE THREAD

**Issue by rward3182** [rward3182/PNG#2]

**Comment by matthewjreeve** [comment]
Upgraded to new ODK syntax, fixed issue with decedents name (needs testing), and have added in all that's needed in 'survey' sheet and entered data in choices sheet.

[SmartVA_PNG_v3.zip](https://github.com/rward3182/PNG/files/1464535/SmartVA_PNG_v3.zip)

Remaining to-do:
-test decedents name issue
- speak to Ila Rouka and check issue with final two provinces (highlighted in yellow on choices sheet) as to whether code should begin with 21 or 07, and 22 or 09 respectively.
- test cascading selects

**Comment by rward3182** [comment]
This issue is now with IIa. I have shown him and explained it. The cascade looks OK in my testing. Well done Matt!

**Comment by RomainSanton** [comment]
Thanks Matt and Roger. 
It makes definitely more sense that those codes should begin with 21 and 22. I have double checked with people here in PNG.  
If you do not get a straight forward answer from Ila, please proceed to the change and send me the final version as soon as possible so that we can install it on the tablets during the IT training tomorrow. 
As the discussion on notification goes, it seems like we will have to add the "wards" here too. And they also have some codes, that I am trying to figure out with the provincial director now. 
This system of notification through ward recorders will need additional discussions. We also have the upcoming CRVS legal review workshop. 
In any case, some more work ahead of us to modify and finalize the questionnaire. 
In its current form, the questionnaire is good enough for the implementation of the pilot in Alotau District. Bill will be going to Alotau very regularly (every month potentially) to supervise the VA work and we can use that to get feedback to improve the questionnaire before the next batch. 
Many thanks to you both for all the great work!

**Comment by matthewjreeve** [comment]
Thanks both and glad to hear it works.

My strong feeling is that we need to be very sure that the codes we are using match what is used in DHIS2 particularly, otherwise we lose all the benefit of being able to merge data. So we need to verify what the true codes are with someone who has access to the DHIS2 code system.

Interestingly, it looks to me like those two provinces (21 and 22) might originally have been part of provinces 07 and 09 respectively and were separated out at some point. I’m just looking at the district codes, which don’t overlap  - eg Province 07 (Southern Highlands) has district codes 01,02, 03, and 06, 07, while province 21 (Hela) has district codes 04,05 and 08. I’ll email this observation to Ilia.

It would be good to have other people reviewing that facilities and code list while you are there Romain, if you come across anyone who knows this stuff, as a cross-check with Ilia. The front-end works find but I’m nervous that we get the right corresponding codes in the database!

Cheers,

Matt

**Comment by rward3182** [comment]
LIyla confirmed codes. Tested form and working Now with Hafiz
